pipeline:
  identifier: Build_mydeentesla_harness_1704822186111
  name: Build harness
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: mydeentesla/harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: mvn install
                  spec:
                    shell: Sh
                    command: mvn install
                  timeout: ""
                  type: Run
                  description: maven package
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
